version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wordcloud
    ports:
      - "5432:5432"

  word-cloud-core-server:
    image: "word-cloud-core-server:latest"
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - variables.env

  word-cloud-server-worker:
    image: "word-cloud-server-worker:latest"
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - variables.env

  word-cloud-client:
    image: "word-cloud-client:latest"
    ports:
      - "3000:80"