version: '3'

services:
  word-cloud-client:
    build:
      context: word-cloud-client
      dockerfile: ../word-cloud-client/Dockerfile
    volumes:
      - website:/website/build/
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - website:/usr/share/nginx/html/website
    depends_on:
      - word-cloud-client

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wordcloud
    ports:
      - "5432:5432"

  word-cloud-core-server:
    build:
      context: word-cloud-core-server
      dockerfile: ../word-cloud-core-server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - variables.env

  word-cloud-server-worker:
    build:
      context: word-cloud-server-worker
      dockerfile: ../word-cloud-server-worker/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - variables.env

volumes:
  website: